WITH RECURSIVE HOURS AS(
    SELECT 0 AS TIME
    UNION ALL
    SELECT TIME + 1
    FROM HOURS
    WHERE TIME < 23
)

SELECT H.TIME AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A
RIGHT JOIN HOURS H
ON H.TIME = HOUR(A.DATETIME)
GROUP BY H.TIME
ORDER BY H.TIME;