SELECT C.CAR_ID, C.CAR_TYPE, TRUNCATE(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100,0) AS FEE
FROM(
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE < '2022-11-30'
            AND END_DATE > '2022-11-01'
    )
    AND CAR_TYPE IN ('세단', 'SUV')
) C
JOIN (
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE IN ('세단', 'SUV') 
        AND DURATION_TYPE LIKE '30%'
) P
ON C.CAR_TYPE = P.CAR_TYPE
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
