-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE), 2) AS AVGSCORE
FROM REST_INFO RI
JOIN REST_REVIEW RR
ON RI.REST_ID = RR.REST_ID
WHERE SUBSTR(RI.ADDRESS, 1, 2) = '서울'
GROUP BY REST_ID
ORDER BY AVGSCORE DESC, RI.FAVORITES DESC