-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A
JOIN (SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE LIKE '____-10-__') B
ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = '세단'
ORDER BY A.CAR_ID DESC;