SELECT YEAR(S.SALES_DATE) YEAR , MONTH(S.SALES_DATE) MONTH, COUNT(DISTINCT J.USER_ID), ROUND(COUNT(DISTINCT J.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1)
FROM ONLINE_SALE S
JOIN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021) J
ON S.USER_ID = J.USER_ID
GROUP BY 1, 2
ORDER BY 1, 2