-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE*FO.AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT FROM FOOD_ORDER WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31' GROUP BY PRODUCT_ID) FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID