SELECT J.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUMS FROM JULY GROUP BY FLAVOR) J
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUMS FROM FIRST_HALF GROUP BY FLAVOR) F
ON J.FLAVOR = F.FLAVOR
ORDER BY J.SUMS + F.SUMS DESC
LIMIT 3