SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS R_DATE
FROM REST_REVIEW R
JOIN (SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW_COUNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY REVIEW_COUNT DESC
LIMIT 1) D
ON R.MEMBER_ID = D.MEMBER_ID
JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
ORDER BY R_DATE, REVIEW_TEXT