SELECT CHILD.ITEM_ID, CHILD.ITEM_NAME, CHILD.RARITY
FROM ITEM_INFO CHILD
WHERE CHILD.ITEM_ID IN (
    SELECT TREE.ITEM_ID
    FROM ITEM_TREE TREE
    JOIN ITEM_INFO PARENT
    ON TREE.PARENT_ITEM_ID = PARENT.ITEM_ID
    WHERE PARENT.RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC;