-- 코드를 입력하세요
SELECT FF.FLAVOR
FROM (SELECT F.FLAVOR, SUM(F.TOTAL_ORDER) AS SUM FROM FIRST_HALF F GROUP BY F.FLAVOR) FF
JOIN (SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) AS SUM FROM JULY J GROUP BY J.FLAVOR) JJ
ON FF.FLAVOR = JJ.FLAVOR
GROUP BY FLAVOR
ORDER BY FF.SUM + JJ.SUM DESC
LIMIT 3;
